[package]
name = "HyprBind"
version = "0.1.1"
edition = "2024"
license = "MIT"

[dependencies]
eframe = "0.33.0"
image = "0.25"
egui = "0.33.0"
egui_extras = "0.33.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nerd_font = "0.2.8"
