[toolchain]
channel = "stable"

components = [
    "rustfmt",
    "clippy",
    "rust-analysis",
    "rust-docs",
    "rust-src",
    "cargo-audit"
]

targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu"
]
